### ISSUE TITLE
Random Jokes Chrome Extension

### ISSUE THREAD

**Issue by Anubhab2002** [WarriorWhoCodesCommunity/dad-jokes-extension#1]
Hey @AnkushSinghGandhi , can you assign this project to me? I will make a simple dad-jokes-extension which will show random jokes in pop-up when clicked on the the extension icon in chrome.

Any suggestions or points are welcome. I will follow the guidelines provided by you.

Please assign this to my as a part of my **HACKTOBERFEST2021** journey.

**Comment by Anubhab2002** [comment]
Thank you for assigning it to me. Could you add hacktoberfest label to the issue?

**Comment by AnkushSinghGandhi** [comment]
This "issue" has been assigned to you; there is no need to add the hacktoberfest label on the issue because the repository already has the hacktoberfest label on it. :+1:

**Comment by Anubhab2002** [comment]
I will try to give my best!

**Comment by AnkushSinghGandhi** [comment]
You can ask help from someone on the CodeVisor server. This manner, you may assist someone in beginning their journey in open source, as the main goal of this organisation is to collaborate rather than code. :smile:

**Comment by Anubhab2002** [comment]
Hey @AnkushSinghGandhi, I have completed building the chrome extension and its working smoothly. Shall I send a PR?
Here are some samples:
- a random joke displayed when you click on the extension
![Screenshot from 2021-10-08 17-07-42](https://user-images.githubusercontent.com/84004920/136550625-3eadf70a-9576-4763-801a-49a5727cd2c3.png)
- you can click on like if you liked the joke
![Screenshot from 2021-10-08 17-08-03](https://user-images.githubusercontent.com/84004920/136550724-ccd561a5-39df-4bbe-805e-6bf2d361c0d6.png)
- when there is no internet connection then you are shown offline status
![Screenshot from 2021-10-08 17-04-16](https://user-images.githubusercontent.com/84004920/136550812-3563b6fd-fd3e-4d41-98e2-4dca10cbd5c4.png)
- you can click on 'New Joke' to fetch a fresh joke
- I have also liked the github repository of the project as a footer.

**Comment by AnkushSinghGandhi** [comment]
Yeah you can raise a PR :+1:

**Comment by Anubhab2002** [comment]
@AnkushSinghGandhi done

**Comment by AnkushSinghGandhi** [comment]
@Anubhab2002 Thanks for the PR! Please give us some time to review it.

**Comment by Anubhab2002** [comment]
@AnkushSinghGandhi , is it alright? Did you review it?

**Comment by AnkushSinghGandhi** [comment]
Merged your PR :+1:
