### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by AnkushSinghGandhi** [WarriorWhoCodesCommunity/dad-jokes-extension#4]
Update Readme to look something like [this](https://github.com/CodeVisors/codevisor-profile-launcher/blob/main/README.md).

**Comment by sugato1398** [comment]
hi, may I take it?

**Comment by Anubhab2002** [comment]
Assign this to me. I will do it!!

**Comment by AnkushSinghGandhi** [comment]
@sugato1398 asssigned it to you. :smiley:

**Comment by AnkushSinghGandhi** [comment]
@Anubhab2002 you've already contributed a lot to this repository. Please consider check-in in some other repositories so other contributors can try this one. :smile:

**Comment by sugato1398** [comment]
hi @AnkushSinghGandhi  , can you tell me whom to add as the project maintainers? ive added you and @Anubhab2002  for now, let me know if some changes are required

**Comment by Anubhab2002** [comment]
> @Anubhab2002 you've already contributed a lot to this repository. Please consider check-in in some other repositories so other contributors can try this one. 😄

Ohh, no problem, @AnkushSinghGandhi ,  I messaged just in case.

**Comment by AnkushSinghGandhi** [comment]
@sugato1398 yeah that's great :+1:
